default_config:
logger:
  default: error
  logs:
    custom_components.esxi_stats: debug


esxi_stats:
  host: IPADDRESS
  username: USERNAME
  password: PASSWORD
  monitored_conditions:
    - hosts
    - vms
    - datastores